#include "base/prerequisites.h"
#include "core/core.h"
#include "../vulkan_rhi.h"
#include "interface/rhi/rhi_enums.h"
namespace Arieo
{
    ARIEO_ENUM_MAPPER(Interface::RHI::BufferUsageBitFlags, VkBufferUsageFlagBits)
    {
        {Arieo::Interface::RHI::BufferUsageBitFlags::UNKNOWN, VkBufferUsageFlagBits(0)},
        {Arieo::Interface::RHI::BufferUsageBitFlags::TRANSFER_SRC, VK_BUFFER_USAGE_TRANSFER_SRC_BIT},
        {Arieo::Interface::RHI::BufferUsageBitFlags::TRANSFER_DST, VK_BUFFER_USAGE_TRANSFER_DST_BIT},
        {Arieo::Interface::RHI::BufferUsageBitFlags::UNIFORM_TEXEL, VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT},
        {Arieo::Interface::RHI::BufferUsageBitFlags::STORAGE_TEXEL, VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT},
        {Arieo::Interface::RHI::BufferUsageBitFlags::UNIFORM, VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT},
        {Arieo::Interface::RHI::BufferUsageBitFlags::STORAGE, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT},
        {Arieo::Interface::RHI::BufferUsageBitFlags::INDEX, VK_BUFFER_USAGE_INDEX_BUFFER_BIT},
        {Arieo::Interface::RHI::BufferUsageBitFlags::VERTEX, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT},
        {Arieo::Interface::RHI::BufferUsageBitFlags::INDIRECT, VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT},
    };

    ARIEO_ENUM_MAPPER(Interface::RHI::ImageTiling, VkImageTiling)
    {
        {Arieo::Interface::RHI::ImageTiling::OPTIMAL, VK_IMAGE_TILING_OPTIMAL},
        {Arieo::Interface::RHI::ImageTiling::LINEAR, VK_IMAGE_TILING_LINEAR},
        {Arieo::Interface::RHI::ImageTiling::DRM_FORMAT_MODIFIER_EXT, VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT},
    };

    ARIEO_ENUM_MAPPER(Interface::RHI::MemoryUsage, VmaMemoryUsage)
    {
        {Arieo::Interface::RHI::MemoryUsage::UNKNOWN, VMA_MEMORY_USAGE_UNKNOWN},
        {Arieo::Interface::RHI::MemoryUsage::GPU_LAZILY_ALLOCATED, VMA_MEMORY_USAGE_GPU_LAZILY_ALLOCATED},
        {Arieo::Interface::RHI::MemoryUsage::AUTO, VMA_MEMORY_USAGE_AUTO},
        {Arieo::Interface::RHI::MemoryUsage::AUTO_PREFER_DEVICE, VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE},
        {Arieo::Interface::RHI::MemoryUsage::AUTO_PREFER_HOST, VMA_MEMORY_USAGE_AUTO_PREFER_HOST},
    };

    ARIEO_ENUM_MAPPER(Interface::RHI::BufferAllocationFlags, VmaAllocationCreateFlags)
    {
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_DEDICATED_MEMORY_BIT,                     VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_NEVER_ALLOCATE_BIT,                       VMA_ALLOCATION_CREATE_NEVER_ALLOCATE_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_MAPPED_BIT,                               VMA_ALLOCATION_CREATE_MAPPED_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_USER_DATA_COPY_STRING_BIT,                VMA_ALLOCATION_CREATE_USER_DATA_COPY_STRING_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_UPPER_ADDRESS_BIT,                        VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_DONT_BIND_BIT,                            VMA_ALLOCATION_CREATE_DONT_BIND_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_WITHIN_BUDGET_BIT,                        VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_CAN_ALIAS_BIT,                            VMA_ALLOCATION_CREATE_CAN_ALIAS_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT,         VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_HOST_ACCESS_RANDOM_BIT,                   VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT,   VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_STRATEGY_MIN_MEMORY_BIT,                  VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_STRATEGY_MIN_TIME_BIT,                    VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT},
        { Arieo::Interface::RHI::BufferAllocationFlags::CREATE_STRATEGY_MIN_OFFSET_BIT,                  VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT},
    };

    ARIEO_ENUM_MAPPER(Interface::RHI::ImageAspectFlags, VkImageAspectFlags)
    {
        { Arieo::Interface::RHI::ImageAspectFlags::NONE, VK_IMAGE_ASPECT_NONE },
        { Arieo::Interface::RHI::ImageAspectFlags::COLOR_BIT,    VK_IMAGE_ASPECT_COLOR_BIT },
        { Arieo::Interface::RHI::ImageAspectFlags::DEPTH_BIT,    VK_IMAGE_ASPECT_DEPTH_BIT },
        { Arieo::Interface::RHI::ImageAspectFlags::STENCIL_BIT,  VK_IMAGE_ASPECT_STENCIL_BIT },
        { Arieo::Interface::RHI::ImageAspectFlags::METADATA_BIT, VK_IMAGE_ASPECT_METADATA_BIT },
        { Arieo::Interface::RHI::ImageAspectFlags::PLANE_0_BIT,  VK_IMAGE_ASPECT_PLANE_0_BIT },
        { Arieo::Interface::RHI::ImageAspectFlags::PLANE_1_BIT,  VK_IMAGE_ASPECT_PLANE_1_BIT },
        { Arieo::Interface::RHI::ImageAspectFlags::PLANE_2_BIT,  VK_IMAGE_ASPECT_PLANE_2_BIT },
        { Arieo::Interface::RHI::ImageAspectFlags::MEMORY_PLANE_0_BIT_EXT,   VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT },
        { Arieo::Interface::RHI::ImageAspectFlags::MEMORY_PLANE_1_BIT_EXT,   VK_IMAGE_ASPECT_MEMORY_PLANE_1_BIT_EXT },
        { Arieo::Interface::RHI::ImageAspectFlags::MEMORY_PLANE_2_BIT_EXT,   VK_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT },
        { Arieo::Interface::RHI::ImageAspectFlags::MEMORY_PLANE_3_BIT_EXT,   VK_IMAGE_ASPECT_MEMORY_PLANE_3_BIT_EXT },
    };

    ARIEO_ENUM_MAPPER(Interface::RHI::FormatFeatureFlags, VkFormatFeatureFlags)
    {
        { Arieo::Interface::RHI::FormatFeatureFlags::SAMPLED_IMAGE_BIT,  VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::STORAGE_IMAGE_BIT,  VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::STORAGE_IMAGE_ATOMIC_BIT,   VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::UNIFORM_TEXEL_BUFFER_BIT,   VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::STORAGE_TEXEL_BUFFER_BIT,   VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::STORAGE_TEXEL_BUFFER_ATOMIC_BIT,    VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::VERTEX_BUFFER_BIT,  VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::COLOR_ATTACHMENT_BIT,   VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::COLOR_ATTACHMENT_BLEND_BIT, VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::DEPTH_STENCIL_ATTACHMENT_BIT,   VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::BLIT_SRC_BIT,   VK_FORMAT_FEATURE_BLIT_SRC_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::BLIT_DST_BIT,   VK_FORMAT_FEATURE_BLIT_DST_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::SAMPLED_IMAGE_FILTER_LINEAR_BIT,    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::TRANSFER_SRC_BIT,   VK_FORMAT_FEATURE_TRANSFER_SRC_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::TRANSFER_DST_BIT,   VK_FORMAT_FEATURE_TRANSFER_DST_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::MIDPOINT_CHROMA_SAMPLES_BIT,    VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT,   VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT,  VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT,  VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT,    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::DISJOINT_BIT,   VK_FORMAT_FEATURE_DISJOINT_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::COSITED_CHROMA_SAMPLES_BIT, VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::SAMPLED_IMAGE_FILTER_MINMAX_BIT,    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT },
        { Arieo::Interface::RHI::FormatFeatureFlags::VIDEO_DECODE_OUTPUT_BIT_KHR,    VK_FORMAT_FEATURE_VIDEO_DECODE_OUTPUT_BIT_KHR },
        { Arieo::Interface::RHI::FormatFeatureFlags::VIDEO_DECODE_DPB_BIT_KHR,   VK_FORMAT_FEATURE_VIDEO_DECODE_DPB_BIT_KHR },
        { Arieo::Interface::RHI::FormatFeatureFlags::ACCELERATION_STRUCTURE_VERTEX_BUFFER_BIT_KHR,   VK_FORMAT_FEATURE_ACCELERATION_STRUCTURE_VERTEX_BUFFER_BIT_KHR },
        { Arieo::Interface::RHI::FormatFeatureFlags::SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT, VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT },
        { Arieo::Interface::RHI::FormatFeatureFlags::FRAGMENT_DENSITY_MAP_BIT_EXT,   VK_FORMAT_FEATURE_FRAGMENT_DENSITY_MAP_BIT_EXT },
        { Arieo::Interface::RHI::FormatFeatureFlags::FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,   VK_FORMAT_FEATURE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR },
        { Arieo::Interface::RHI::FormatFeatureFlags::VIDEO_ENCODE_INPUT_BIT_KHR, VK_FORMAT_FEATURE_VIDEO_ENCODE_INPUT_BIT_KHR },
        { Arieo::Interface::RHI::FormatFeatureFlags::VIDEO_ENCODE_DPB_BIT_KHR,   VK_FORMAT_FEATURE_VIDEO_ENCODE_DPB_BIT_KHR },
    };
    
    ARIEO_ENUM_MAPPER(Interface::RHI::ImageUsageFlags, VkImageUsageFlags)
    {
        { Arieo::Interface::RHI::ImageUsageFlags::TRANSFER_SRC_BIT,  VK_IMAGE_USAGE_TRANSFER_SRC_BIT },
        { Arieo::Interface::RHI::ImageUsageFlags::TRANSFER_DST_BIT,  VK_IMAGE_USAGE_TRANSFER_DST_BIT },
        { Arieo::Interface::RHI::ImageUsageFlags::SAMPLED_BIT,   VK_IMAGE_USAGE_SAMPLED_BIT },
        { Arieo::Interface::RHI::ImageUsageFlags::STORAGE_BIT,   VK_IMAGE_USAGE_STORAGE_BIT },
        { Arieo::Interface::RHI::ImageUsageFlags::COLOR_ATTACHMENT_BIT,  VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT },
        { Arieo::Interface::RHI::ImageUsageFlags::DEPTH_STENCIL_ATTACHMENT_BIT,  VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT },
        { Arieo::Interface::RHI::ImageUsageFlags::TRANSIENT_ATTACHMENT_BIT,  VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT },
        { Arieo::Interface::RHI::ImageUsageFlags::INPUT_ATTACHMENT_BIT,  VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT },
        //{ Arieo::Interface::RHI::ImageUsageFlags::HOST_TRANSFER_BIT,     VK_IMAGE_USAGE_HOST_TRANSFER_BIT },
        { Arieo::Interface::RHI::ImageUsageFlags::VIDEO_DECODE_DST_BIT_KHR,  VK_IMAGE_USAGE_VIDEO_DECODE_DST_BIT_KHR },
        { Arieo::Interface::RHI::ImageUsageFlags::VIDEO_DECODE_SRC_BIT_KHR,  VK_IMAGE_USAGE_VIDEO_DECODE_SRC_BIT_KHR },
        { Arieo::Interface::RHI::ImageUsageFlags::VIDEO_DECODE_DPB_BIT_KHR,  VK_IMAGE_USAGE_VIDEO_DECODE_DPB_BIT_KHR },
        { Arieo::Interface::RHI::ImageUsageFlags::FRAGMENT_DENSITY_MAP_BIT_EXT,  VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT },
        { Arieo::Interface::RHI::ImageUsageFlags::FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,  VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR },
        { Arieo::Interface::RHI::ImageUsageFlags::VIDEO_ENCODE_DST_BIT_KHR,  VK_IMAGE_USAGE_VIDEO_ENCODE_DST_BIT_KHR },
        { Arieo::Interface::RHI::ImageUsageFlags::VIDEO_ENCODE_SRC_BIT_KHR,  VK_IMAGE_USAGE_VIDEO_ENCODE_SRC_BIT_KHR },
        { Arieo::Interface::RHI::ImageUsageFlags::VIDEO_ENCODE_DPB_BIT_KHR,  VK_IMAGE_USAGE_VIDEO_ENCODE_DPB_BIT_KHR },
        { Arieo::Interface::RHI::ImageUsageFlags::ATTACHMENT_FEEDBACK_LOOP_BIT_EXT,  VK_IMAGE_USAGE_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT },
        { Arieo::Interface::RHI::ImageUsageFlags::INVOCATION_MASK_BIT_HUAWEI,    VK_IMAGE_USAGE_INVOCATION_MASK_BIT_HUAWEI },
        { Arieo::Interface::RHI::ImageUsageFlags::SAMPLE_WEIGHT_BIT_QCOM,    VK_IMAGE_USAGE_SAMPLE_WEIGHT_BIT_QCOM },
        { Arieo::Interface::RHI::ImageUsageFlags::SAMPLE_BLOCK_MATCH_BIT_QCOM,   VK_IMAGE_USAGE_SAMPLE_BLOCK_MATCH_BIT_QCOM },
        // { Arieo::Interface::RHI::ImageUsageFlags::VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR,   VK_IMAGE_USAGE_VIDEO_ENCODE_QUANTIZATION_DELTA_MAP_BIT_KHR },
        // { Arieo::Interface::RHI::ImageUsageFlags::VIDEO_ENCODE_EMPHASIS_MAP_BIT_KHR,     VK_IMAGE_USAGE_VIDEO_ENCODE_EMPHASIS_MAP_BIT_KHR },
    };

    ARIEO_ENUM_MAPPER(Interface::RHI::Format, VkFormat)
    {
        { Arieo::Interface::RHI::Format::R4G4_UNORM_PACK8, VK_FORMAT_R4G4_UNORM_PACK8 }, 
        { Arieo::Interface::RHI::Format::R4G4B4A4_UNORM_PACK16, VK_FORMAT_R4G4B4A4_UNORM_PACK16 }, 
        { Arieo::Interface::RHI::Format::B4G4R4A4_UNORM_PACK16, VK_FORMAT_B4G4R4A4_UNORM_PACK16 }, 
        { Arieo::Interface::RHI::Format::R5G6B5_UNORM_PACK16, VK_FORMAT_R5G6B5_UNORM_PACK16 }, 
        { Arieo::Interface::RHI::Format::B5G6R5_UNORM_PACK16, VK_FORMAT_B5G6R5_UNORM_PACK16 }, 
        { Arieo::Interface::RHI::Format::R5G5B5A1_UNORM_PACK16, VK_FORMAT_R5G5B5A1_UNORM_PACK16 }, 
        { Arieo::Interface::RHI::Format::B5G5R5A1_UNORM_PACK16, VK_FORMAT_B5G5R5A1_UNORM_PACK16 }, 
        { Arieo::Interface::RHI::Format::A1R5G5B5_UNORM_PACK16, VK_FORMAT_A1R5G5B5_UNORM_PACK16 }, 
        { Arieo::Interface::RHI::Format::R8_UNORM, VK_FORMAT_R8_UNORM }, 
        { Arieo::Interface::RHI::Format::R8_SNORM, VK_FORMAT_R8_SNORM }, 
        { Arieo::Interface::RHI::Format::R8_USCALED, VK_FORMAT_R8_USCALED }, 
        { Arieo::Interface::RHI::Format::R8_SSCALED, VK_FORMAT_R8_SSCALED }, 
        { Arieo::Interface::RHI::Format::R8_UINT, VK_FORMAT_R8_UINT }, 
        { Arieo::Interface::RHI::Format::R8_SINT, VK_FORMAT_R8_SINT }, 
        { Arieo::Interface::RHI::Format::R8_SRGB, VK_FORMAT_R8_SRGB }, 
        { Arieo::Interface::RHI::Format::R8G8_UNORM, VK_FORMAT_R8G8_UNORM }, 
        { Arieo::Interface::RHI::Format::R8G8_SNORM, VK_FORMAT_R8G8_SNORM }, 
        { Arieo::Interface::RHI::Format::R8G8_USCALED, VK_FORMAT_R8G8_USCALED }, 
        { Arieo::Interface::RHI::Format::R8G8_SSCALED, VK_FORMAT_R8G8_SSCALED }, 
        { Arieo::Interface::RHI::Format::R8G8_UINT, VK_FORMAT_R8G8_UINT }, 
        { Arieo::Interface::RHI::Format::R8G8_SINT, VK_FORMAT_R8G8_SINT }, 
        { Arieo::Interface::RHI::Format::R8G8_SRGB, VK_FORMAT_R8G8_SRGB }, 
        { Arieo::Interface::RHI::Format::R8G8B8_UNORM, VK_FORMAT_R8G8B8_UNORM }, 
        { Arieo::Interface::RHI::Format::R8G8B8_SNORM, VK_FORMAT_R8G8B8_SNORM }, 
        { Arieo::Interface::RHI::Format::R8G8B8_USCALED, VK_FORMAT_R8G8B8_USCALED }, 
        { Arieo::Interface::RHI::Format::R8G8B8_SSCALED, VK_FORMAT_R8G8B8_SSCALED }, 
        { Arieo::Interface::RHI::Format::R8G8B8_UINT, VK_FORMAT_R8G8B8_UINT }, 
        { Arieo::Interface::RHI::Format::R8G8B8_SINT, VK_FORMAT_R8G8B8_SINT }, 
        { Arieo::Interface::RHI::Format::R8G8B8_SRGB, VK_FORMAT_R8G8B8_SRGB }, 
        { Arieo::Interface::RHI::Format::B8G8R8_UNORM, VK_FORMAT_B8G8R8_UNORM }, 
        { Arieo::Interface::RHI::Format::B8G8R8_SNORM, VK_FORMAT_B8G8R8_SNORM }, 
        { Arieo::Interface::RHI::Format::B8G8R8_USCALED, VK_FORMAT_B8G8R8_USCALED }, 
        { Arieo::Interface::RHI::Format::B8G8R8_SSCALED, VK_FORMAT_B8G8R8_SSCALED }, 
        { Arieo::Interface::RHI::Format::B8G8R8_UINT, VK_FORMAT_B8G8R8_UINT }, 
        { Arieo::Interface::RHI::Format::B8G8R8_SINT, VK_FORMAT_B8G8R8_SINT }, 
        { Arieo::Interface::RHI::Format::B8G8R8_SRGB, VK_FORMAT_B8G8R8_SRGB }, 
        { Arieo::Interface::RHI::Format::R8G8B8A8_UNORM, VK_FORMAT_R8G8B8A8_UNORM }, 
        { Arieo::Interface::RHI::Format::R8G8B8A8_SNORM, VK_FORMAT_R8G8B8A8_SNORM }, 
        { Arieo::Interface::RHI::Format::R8G8B8A8_USCALED, VK_FORMAT_R8G8B8A8_USCALED }, 
        { Arieo::Interface::RHI::Format::R8G8B8A8_SSCALED, VK_FORMAT_R8G8B8A8_SSCALED }, 
        { Arieo::Interface::RHI::Format::R8G8B8A8_UINT, VK_FORMAT_R8G8B8A8_UINT }, 
        { Arieo::Interface::RHI::Format::R8G8B8A8_SINT, VK_FORMAT_R8G8B8A8_SINT }, 
        { Arieo::Interface::RHI::Format::R8G8B8A8_SRGB, VK_FORMAT_R8G8B8A8_SRGB }, 
        { Arieo::Interface::RHI::Format::B8G8R8A8_UNORM, VK_FORMAT_B8G8R8A8_UNORM }, 
        { Arieo::Interface::RHI::Format::B8G8R8A8_SNORM, VK_FORMAT_B8G8R8A8_SNORM }, 
        { Arieo::Interface::RHI::Format::B8G8R8A8_USCALED, VK_FORMAT_B8G8R8A8_USCALED }, 
        { Arieo::Interface::RHI::Format::B8G8R8A8_SSCALED, VK_FORMAT_B8G8R8A8_SSCALED }, 
        { Arieo::Interface::RHI::Format::B8G8R8A8_UINT, VK_FORMAT_B8G8R8A8_UINT }, 
        { Arieo::Interface::RHI::Format::B8G8R8A8_SINT, VK_FORMAT_B8G8R8A8_SINT }, 
        { Arieo::Interface::RHI::Format::B8G8R8A8_SRGB, VK_FORMAT_B8G8R8A8_SRGB }, 
        { Arieo::Interface::RHI::Format::A8B8G8R8_UNORM_PACK32, VK_FORMAT_A8B8G8R8_UNORM_PACK32 }, 
        { Arieo::Interface::RHI::Format::A8B8G8R8_SNORM_PACK32, VK_FORMAT_A8B8G8R8_SNORM_PACK32 }, 
        { Arieo::Interface::RHI::Format::A8B8G8R8_USCALED_PACK32, VK_FORMAT_A8B8G8R8_USCALED_PACK32 }, 
        { Arieo::Interface::RHI::Format::A8B8G8R8_SSCALED_PACK32, VK_FORMAT_A8B8G8R8_SSCALED_PACK32 }, 
        { Arieo::Interface::RHI::Format::A8B8G8R8_UINT_PACK32, VK_FORMAT_A8B8G8R8_UINT_PACK32 }, 
        { Arieo::Interface::RHI::Format::A8B8G8R8_SINT_PACK32, VK_FORMAT_A8B8G8R8_SINT_PACK32 }, 
        { Arieo::Interface::RHI::Format::A8B8G8R8_SRGB_PACK32, VK_FORMAT_A8B8G8R8_SRGB_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2R10G10B10_UNORM_PACK32, VK_FORMAT_A2R10G10B10_UNORM_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2R10G10B10_SNORM_PACK32, VK_FORMAT_A2R10G10B10_SNORM_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2R10G10B10_USCALED_PACK32, VK_FORMAT_A2R10G10B10_USCALED_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2R10G10B10_SSCALED_PACK32, VK_FORMAT_A2R10G10B10_SSCALED_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2R10G10B10_UINT_PACK32, VK_FORMAT_A2R10G10B10_UINT_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2R10G10B10_SINT_PACK32, VK_FORMAT_A2R10G10B10_SINT_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2B10G10R10_UNORM_PACK32, VK_FORMAT_A2B10G10R10_UNORM_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2B10G10R10_SNORM_PACK32, VK_FORMAT_A2B10G10R10_SNORM_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2B10G10R10_USCALED_PACK32, VK_FORMAT_A2B10G10R10_USCALED_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2B10G10R10_SSCALED_PACK32, VK_FORMAT_A2B10G10R10_SSCALED_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2B10G10R10_UINT_PACK32, VK_FORMAT_A2B10G10R10_UINT_PACK32 }, 
        { Arieo::Interface::RHI::Format::A2B10G10R10_SINT_PACK32, VK_FORMAT_A2B10G10R10_SINT_PACK32 }, 
        { Arieo::Interface::RHI::Format::R16_UNORM, VK_FORMAT_R16_UNORM }, 
        { Arieo::Interface::RHI::Format::R16_SNORM, VK_FORMAT_R16_SNORM }, 
        { Arieo::Interface::RHI::Format::R16_USCALED, VK_FORMAT_R16_USCALED }, 
        { Arieo::Interface::RHI::Format::R16_SSCALED, VK_FORMAT_R16_SSCALED }, 
        { Arieo::Interface::RHI::Format::R16_UINT, VK_FORMAT_R16_UINT }, 
        { Arieo::Interface::RHI::Format::R16_SINT, VK_FORMAT_R16_SINT }, 
        { Arieo::Interface::RHI::Format::R16_SFLOAT, VK_FORMAT_R16_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R16G16_UNORM, VK_FORMAT_R16G16_UNORM }, 
        { Arieo::Interface::RHI::Format::R16G16_SNORM, VK_FORMAT_R16G16_SNORM }, 
        { Arieo::Interface::RHI::Format::R16G16_USCALED, VK_FORMAT_R16G16_USCALED }, 
        { Arieo::Interface::RHI::Format::R16G16_SSCALED, VK_FORMAT_R16G16_SSCALED }, 
        { Arieo::Interface::RHI::Format::R16G16_UINT, VK_FORMAT_R16G16_UINT }, 
        { Arieo::Interface::RHI::Format::R16G16_SINT, VK_FORMAT_R16G16_SINT }, 
        { Arieo::Interface::RHI::Format::R16G16_SFLOAT, VK_FORMAT_R16G16_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R16G16B16_UNORM, VK_FORMAT_R16G16B16_UNORM }, 
        { Arieo::Interface::RHI::Format::R16G16B16_SNORM, VK_FORMAT_R16G16B16_SNORM }, 
        { Arieo::Interface::RHI::Format::R16G16B16_USCALED, VK_FORMAT_R16G16B16_USCALED }, 
        { Arieo::Interface::RHI::Format::R16G16B16_SSCALED, VK_FORMAT_R16G16B16_SSCALED }, 
        { Arieo::Interface::RHI::Format::R16G16B16_UINT, VK_FORMAT_R16G16B16_UINT }, 
        { Arieo::Interface::RHI::Format::R16G16B16_SINT, VK_FORMAT_R16G16B16_SINT }, 
        { Arieo::Interface::RHI::Format::R16G16B16_SFLOAT, VK_FORMAT_R16G16B16_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R16G16B16A16_UNORM, VK_FORMAT_R16G16B16A16_UNORM }, 
        { Arieo::Interface::RHI::Format::R16G16B16A16_SNORM, VK_FORMAT_R16G16B16A16_SNORM }, 
        { Arieo::Interface::RHI::Format::R16G16B16A16_USCALED, VK_FORMAT_R16G16B16A16_USCALED }, 
        { Arieo::Interface::RHI::Format::R16G16B16A16_SSCALED, VK_FORMAT_R16G16B16A16_SSCALED }, 
        { Arieo::Interface::RHI::Format::R16G16B16A16_UINT, VK_FORMAT_R16G16B16A16_UINT }, 
        { Arieo::Interface::RHI::Format::R16G16B16A16_SINT, VK_FORMAT_R16G16B16A16_SINT }, 
        { Arieo::Interface::RHI::Format::R16G16B16A16_SFLOAT, VK_FORMAT_R16G16B16A16_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R32_UINT, VK_FORMAT_R32_UINT }, 
        { Arieo::Interface::RHI::Format::R32_SINT, VK_FORMAT_R32_SINT }, 
        { Arieo::Interface::RHI::Format::R32_SFLOAT, VK_FORMAT_R32_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R32G32_UINT, VK_FORMAT_R32G32_UINT }, 
        { Arieo::Interface::RHI::Format::R32G32_SINT, VK_FORMAT_R32G32_SINT }, 
        { Arieo::Interface::RHI::Format::R32G32_SFLOAT, VK_FORMAT_R32G32_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R32G32B32_UINT, VK_FORMAT_R32G32B32_UINT }, 
        { Arieo::Interface::RHI::Format::R32G32B32_SINT, VK_FORMAT_R32G32B32_SINT }, 
        { Arieo::Interface::RHI::Format::R32G32B32_SFLOAT, VK_FORMAT_R32G32B32_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R32G32B32A32_UINT, VK_FORMAT_R32G32B32A32_UINT }, 
        { Arieo::Interface::RHI::Format::R32G32B32A32_SINT, VK_FORMAT_R32G32B32A32_SINT }, 
        { Arieo::Interface::RHI::Format::R32G32B32A32_SFLOAT, VK_FORMAT_R32G32B32A32_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R64_UINT, VK_FORMAT_R64_UINT }, 
        { Arieo::Interface::RHI::Format::R64_SINT, VK_FORMAT_R64_SINT }, 
        { Arieo::Interface::RHI::Format::R64_SFLOAT, VK_FORMAT_R64_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R64G64_UINT, VK_FORMAT_R64G64_UINT }, 
        { Arieo::Interface::RHI::Format::R64G64_SINT, VK_FORMAT_R64G64_SINT }, 
        { Arieo::Interface::RHI::Format::R64G64_SFLOAT, VK_FORMAT_R64G64_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R64G64B64_UINT, VK_FORMAT_R64G64B64_UINT }, 
        { Arieo::Interface::RHI::Format::R64G64B64_SINT, VK_FORMAT_R64G64B64_SINT }, 
        { Arieo::Interface::RHI::Format::R64G64B64_SFLOAT, VK_FORMAT_R64G64B64_SFLOAT }, 
        { Arieo::Interface::RHI::Format::R64G64B64A64_UINT, VK_FORMAT_R64G64B64A64_UINT }, 
        { Arieo::Interface::RHI::Format::R64G64B64A64_SINT, VK_FORMAT_R64G64B64A64_SINT }, 
        { Arieo::Interface::RHI::Format::R64G64B64A64_SFLOAT, VK_FORMAT_R64G64B64A64_SFLOAT }, 
        { Arieo::Interface::RHI::Format::B10G11R11_UFLOAT_PACK32, VK_FORMAT_B10G11R11_UFLOAT_PACK32 }, 
        { Arieo::Interface::RHI::Format::E5B9G9R9_UFLOAT_PACK32, VK_FORMAT_E5B9G9R9_UFLOAT_PACK32 }, 
        { Arieo::Interface::RHI::Format::D16_UNORM, VK_FORMAT_D16_UNORM }, 
        { Arieo::Interface::RHI::Format::X8_D24_UNORM_PACK32, VK_FORMAT_X8_D24_UNORM_PACK32 }, 
        { Arieo::Interface::RHI::Format::D32_SFLOAT, VK_FORMAT_D32_SFLOAT }, 
        { Arieo::Interface::RHI::Format::S8_UINT, VK_FORMAT_S8_UINT }, 
        { Arieo::Interface::RHI::Format::D16_UNORM_S8_UINT, VK_FORMAT_D16_UNORM_S8_UINT }, 
        { Arieo::Interface::RHI::Format::D24_UNORM_S8_UINT, VK_FORMAT_D24_UNORM_S8_UINT }, 
        { Arieo::Interface::RHI::Format::D32_SFLOAT_S8_UINT, VK_FORMAT_D32_SFLOAT_S8_UINT }, 
        { Arieo::Interface::RHI::Format::BC1_RGB_UNORM_BLOCK, VK_FORMAT_BC1_RGB_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC1_RGB_SRGB_BLOCK, VK_FORMAT_BC1_RGB_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC1_RGBA_UNORM_BLOCK, VK_FORMAT_BC1_RGBA_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC1_RGBA_SRGB_BLOCK, VK_FORMAT_BC1_RGBA_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC2_UNORM_BLOCK, VK_FORMAT_BC2_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC2_SRGB_BLOCK, VK_FORMAT_BC2_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC3_UNORM_BLOCK, VK_FORMAT_BC3_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC3_SRGB_BLOCK, VK_FORMAT_BC3_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC4_UNORM_BLOCK, VK_FORMAT_BC4_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC4_SNORM_BLOCK, VK_FORMAT_BC4_SNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC5_UNORM_BLOCK, VK_FORMAT_BC5_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC5_SNORM_BLOCK, VK_FORMAT_BC5_SNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC6H_UFLOAT_BLOCK, VK_FORMAT_BC6H_UFLOAT_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC6H_SFLOAT_BLOCK, VK_FORMAT_BC6H_SFLOAT_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC7_UNORM_BLOCK, VK_FORMAT_BC7_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::BC7_SRGB_BLOCK, VK_FORMAT_BC7_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ETC2_R8G8B8_UNORM_BLOCK, VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ETC2_R8G8B8_SRGB_BLOCK, VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ETC2_R8G8B8A1_UNORM_BLOCK, VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ETC2_R8G8B8A1_SRGB_BLOCK, VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ETC2_R8G8B8A8_UNORM_BLOCK, VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ETC2_R8G8B8A8_SRGB_BLOCK, VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::EAC_R11_UNORM_BLOCK, VK_FORMAT_EAC_R11_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::EAC_R11_SNORM_BLOCK, VK_FORMAT_EAC_R11_SNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::EAC_R11G11_UNORM_BLOCK, VK_FORMAT_EAC_R11G11_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::EAC_R11G11_SNORM_BLOCK, VK_FORMAT_EAC_R11G11_SNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_4x4_UNORM_BLOCK, VK_FORMAT_ASTC_4x4_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_4x4_SRGB_BLOCK, VK_FORMAT_ASTC_4x4_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_5x4_UNORM_BLOCK, VK_FORMAT_ASTC_5x4_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_5x4_SRGB_BLOCK, VK_FORMAT_ASTC_5x4_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_5x5_UNORM_BLOCK, VK_FORMAT_ASTC_5x5_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_5x5_SRGB_BLOCK, VK_FORMAT_ASTC_5x5_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_6x5_UNORM_BLOCK, VK_FORMAT_ASTC_6x5_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_6x5_SRGB_BLOCK, VK_FORMAT_ASTC_6x5_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_6x6_UNORM_BLOCK, VK_FORMAT_ASTC_6x6_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_6x6_SRGB_BLOCK, VK_FORMAT_ASTC_6x6_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_8x5_UNORM_BLOCK, VK_FORMAT_ASTC_8x5_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_8x5_SRGB_BLOCK, VK_FORMAT_ASTC_8x5_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_8x6_UNORM_BLOCK, VK_FORMAT_ASTC_8x6_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_8x6_SRGB_BLOCK, VK_FORMAT_ASTC_8x6_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_8x8_UNORM_BLOCK, VK_FORMAT_ASTC_8x8_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_8x8_SRGB_BLOCK, VK_FORMAT_ASTC_8x8_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_10x5_UNORM_BLOCK, VK_FORMAT_ASTC_10x5_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_10x5_SRGB_BLOCK, VK_FORMAT_ASTC_10x5_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_10x6_UNORM_BLOCK, VK_FORMAT_ASTC_10x6_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_10x6_SRGB_BLOCK, VK_FORMAT_ASTC_10x6_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_10x8_UNORM_BLOCK, VK_FORMAT_ASTC_10x8_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_10x8_SRGB_BLOCK, VK_FORMAT_ASTC_10x8_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_10x10_UNORM_BLOCK, VK_FORMAT_ASTC_10x10_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_10x10_SRGB_BLOCK, VK_FORMAT_ASTC_10x10_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_12x10_UNORM_BLOCK, VK_FORMAT_ASTC_12x10_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_12x10_SRGB_BLOCK, VK_FORMAT_ASTC_12x10_SRGB_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_12x12_UNORM_BLOCK, VK_FORMAT_ASTC_12x12_UNORM_BLOCK }, 
        { Arieo::Interface::RHI::Format::ASTC_12x12_SRGB_BLOCK, VK_FORMAT_ASTC_12x12_SRGB_BLOCK }
    };
}